### PR TITLE
Add Pull Secret Support for the f5-bigip-ctlr chart

### PR DESCRIPTION
**Pull request by jar361**
This will add Pull Secret Support for the f5-bigip-ctlr chart.

### CODE REVIEW

**Comment by recursivelycurious** [comment]
Hi Johnathan,

Thank you for your PR.

I've just opened #12 to address the contribution guidelines for this repo. They will be substantially the same as on our controller repos, e.g.:
- https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/CONTRIBUTING.md 

And will require the completion of a CLA, which I don't believe we have on file for you? That can be found at:
- http://clouddocs.f5.com/containers/v2/cla_landing.html

And emailed to ContainerConnector_CLA<at>f5.com when completed.

We'll review your PR as soon as the CLA is completed.

Thanks!

**Comment by jar361** [comment]
Completed CLA form has been sent.

**Comment by recursivelycurious** [comment]
Thanks Johnathan, your CLA has been received and is in review.

**Comment by recursivelycurious** [comment]
@jar361 - we'll be running a few tests today/tomorrow and will have an update for you after that. Thanks!

**Comment by recursivelycurious** [comment]
@jar361 - test environment where manual tests are being run is unable to pull private images, even in simple examples for pods only, no use of helm. Appears to be an environment issue. When we have that resolved I will have a further update for you.

**Comment by jar361** [comment]
@recursivelycurious Any update on the testing

**Comment by recursivelycurious** [comment]
@jar361 - We'll have an update for you early next week at the latest. Thank you for your patience.

**Comment by recursivelycurious** [comment]
@jar361 -- if you prefer, we can use https://github.com/recursivelycurious/charts/tree/maint as the basis for a new PR that includes your commit, and close this one.

**Comment by recursivelycurious** [comment]
@jar361 - per yesterday's comment, including your changes in #16 as a cherry-pick and closing this PR. 

Thanks again for your contribution and your patience while we addressed testing.

**Pull request closed without merging**
