### PR TITLE
Repo deprecation notice

### PR DESCRIPTION
**Pull request by sravyap135**
Added deprecation notice in readme

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
A separate repo is much useful .. In fact, I feel k8s-bigip-ctlr operator should also have a separate repo. @sravyap135 Any reason for not maintaining it here and maintaining it as a part of `f5networks/k8s-bigip-ctlr`

**Review by trinaths — APPROVED** [review]
looks good to me.

**Comment by vklohiya** [comment]
@iam-veeramalla , we are ending up creating multiple pull request for same code in two different repository. Hence we are deprecating it.

**Review by vklohiya — APPROVED** [review]
Looks Fine

**Pull request merged**
