### PR TITLE
Fixes for from PR #18 + credentials directory 

### PR DESCRIPTION
**Pull request by chen23**
Includes https://github.com/F5Networks/charts/pull/18

Also updates “stable” template

Adds “credentials directory” for secrets (new default)

### CODE REVIEW

**Comment by mdditt2000** [comment]
@kavitha-f5 @f5tsomanchi dev can you please review and approve @chen23 commits. TY

**Comment by f5tsomanchi** [comment]
@chen23  @rendhalver - Fixes from PR#18, require CLA to be signed. Please find the CLA document at https://clouddocs.f5.com/containers/v2/cla_landing.html. Please submit/email a signed copy of the same to ContainerConnector_CLA@f5.com to consider the fix. Please include your github handle in the CLA email.

**Comment by f5tsomanchi** [comment]
@chen23 - Can you please separate your fix for PR#18. @rendhalver fix requires CLA be signed and also need to attach that CLA in this conversation and I feel it may take time.

**Comment by chen23** [comment]
per your request I have created a separate PR #25

**Comment by trinaths** [comment]
Closing this PR, since changes have been integrated.

**Pull request closed without merging**
